version: '3'

services:
    sytc:
        build:
            context: .
            dockerfile: Dockerfile
        image: jwansek/smallytchannelbot
        network_mode: host
        volumes:
            - ./logs/:/logs/
    cron:
        build:
            context: .
            dockerfile: ./onceaday/Dockerfile
        image: jwansek/smallytchannelbotoad
        network_mode: host