version: '3'

services:
    sytc:
        build:
            context: .
            dockerfile: Dockerfile
        image: jwansek/smallytchannelbot
        networks:
            - db-network
        external_links:
            - mariadb:mysql
    cron:
        build:
            context: .
            dockerfile: ./onceaday/Dockerfile
        image: jwansek/smallytchannelbotoad
        networks:
            - db-network
        external_links:
            - mariadb:mysql

networks:
    db-network:
        external:
            name: mariadb
