services:
    sytc:
        build:
            context: .
            dockerfile: Dockerfile
        image: reg.reaweb.uk/smallytchannelbot
        networks:
            - db-network
        external_links:
            - mariadb:mysql
        volumes:
            - ./config.json:/app/config.json
        restart: unless-stopped

    cron:
        build:
            context: .
            dockerfile: ./cron/Dockerfile
        image: reg.reaweb.uk/smallytchannelbot_cron
        networks:
            - db-network
        external_links:
            - mariadb:mysql
        depends_on:
            - sytc
        volumes:
            - ./config.json:/app/config.json
        restart: unless-stopped

networks:
    db-network:
        external: true
        name: mariadb

